[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fibersim"
version = "0.0.1"
requires-python = ">=3.12"
dependencies = [
  "numpy>=1.26",
  "scipy>=1.12",
  "matplotlib>=3.8",
  "pydantic>=2.5",
  "typer>=0.12",
  "rich>=13.0"
]

[project.optional-dependencies]
gpu = ["cupy-cuda12x>=13.0 ; platform_system == 'Windows'"]

[tool.black]
line-length = 100
